### ISSUE TITLE
Nice to have: bold, italics and underline support

### ISSUE THREAD

**Issue by LaPingvino** [LaPingvino/lexington#1]
https://github.com/LaPingvino/lexington/blob/5861ed4f19c32d01d80921b3a8254b20789ebb5f/pdf/create.go#L43 cannot just replace this with a simple HTML element, because it doesn't seem to be multicell or otherwise respecting the set sizes and going to the next line.

@jung-kurt what would be the canonical way to implement this, if any?

**Comment by jung-kurt** [comment]
Saluton, @LaPingvino!

There is a way to render *very* basic HTML; see [this example](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-HTMLBasicNew) for an example. Instead of `pdf.MultiCell()` you would used `html.Write()`. In order to constrain the output to a certain width you would adjust the margins. The `Basic` in `HTMLBasicNew` could be replaced with `BarelyWorkable`. It gets confused by embedded `<` and `>` characters, and underscored text is not supported (it is reserved for hyperlinks which are supported).

Lexington aspektas bonan projekton. Mi esperas, ke ĝi renkontas multan sukceson!

**Comment by LaPingvino** [comment]
Dankon @jung-kurt for your quick reaction!

I think if you want to improve gofpdf, this is probably a perfect project to test every single thing on, because it literally breaks on every limitation of gofpdf... (Also multilang support... which works for specific language projects but with a command line tool with user input, this is much harder to get right...)

**Comment by LaPingvino** [comment]
Fixed by d196fe0
